apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: y2omyz97p-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:f626e7243d34681c92a4167dd4fcc3b14be42160@sha256:45ab4f7a9c8548a1fdc9e23db8d97f4393f5665ed6b669b63195b028e6c801b2
          name: container-image
